/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EditaisRouteImport } from './routes/editais'
import { Route as IndexRouteImport } from './routes/index'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisRoute = EditaisRouteImport.update({
  id: '/editais',
  path: '/editais',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editais': typeof EditaisRoute
  '/equipe': typeof EquipeRoute
  '/lgpd': typeof LgpdRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editais': typeof EditaisRoute
  '/equipe': typeof EquipeRoute
  '/lgpd': typeof LgpdRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editais': typeof EditaisRoute
  '/equipe': typeof EquipeRoute
  '/lgpd': typeof LgpdRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editais' | '/equipe' | '/lgpd' | '/transparencia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editais' | '/equipe' | '/lgpd' | '/transparencia'
  id: '__root__' | '/' | '/editais' | '/equipe' | '/lgpd' | '/transparencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditaisRoute: typeof EditaisRoute
  EquipeRoute: typeof EquipeRoute
  LgpdRoute: typeof LgpdRoute
  TransparenciaRoute: typeof TransparenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais': {
      id: '/editais'
      path: '/editais'
      fullPath: '/editais'
      preLoaderRoute: typeof EditaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditaisRoute: EditaisRoute,
  EquipeRoute: EquipeRoute,
  LgpdRoute: LgpdRoute,
  TransparenciaRoute: TransparenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
